### PR TITLE
Update PHP versions for Debian 7 and 8

### PR DESCRIPTION
**Pull request by halkyon**
These have been updated to the latest versions recently. See https://packages.debian.org/jessie/php5

### CODE REVIEW

**Comment by philsturgeon** [comment]
Is this a patch version of Debian using these new versions? Me might have to rethink how we do this.

**Comment by halkyon** [comment]
The minor versions are updated frequently via latest package sources when you install the OS or when you run `apt-get update && apt-get upgrade` on a current machine, so this page will most likely always be out of date. The exception seems to be Debian 6 which has always been on 5.3.3.

Perhaps you'd just want to list the major version instead? e.g. 5.6 for Debian 8, 5.4 for Debian 7?

**Comment by philsturgeon** [comment]
This section lists which versions distros _ship with_, not the versions you can update to if you're smart and do stuff to get newer versions. Does this change fit in with that?

**Comment by halkyon** [comment]
Yes, it does :)

**Pull request merged**
