### PR TITLE
Fix browser compatibility issue

### PR DESCRIPTION
**Pull request by colinodell**
https://www.reddit.com/r/PHP/comments/453z4v/phpversionsinfo_now_highlights_php_versions_with/czv232f

### CODE REVIEW

**Comment by colinodell** [comment]
I should note that I'm at work where I don't have Jekyll installed, so I haven't actually tested this change.... (shame on me, right?)

**Comment by philsturgeon** [comment]
Again, can see what anything on Reddit says. :)

**Comment by philsturgeon** [comment]
Ran it locally, didn't seem any more broken.

**Comment by colinodell** [comment]
Ha, sorry about that.  Basically folks on Firefox couldn't see the highlighting because Firefox is lame and doesn't support `.innerText`.

**Comment by philsturgeon** [comment]
Thanks :) Test it live!

-- 
Phil Sturgeon

I talk about turtles, bikes and code over here philsturgeon.uk

**Pull request merged**
