### PR TITLE
Add Ubuntu 15.10 and update Debian versions

### PR DESCRIPTION
**Pull request by josegonzalez**
Info from:

- https://packages.debian.org/wheezy/php/
- https://packages.debian.org/jessie/php/
- http://packages.ubuntu.com/xenial/php5-common

### CODE REVIEW

**Comment by davidyell** [comment]
:+1:

**Comment by philsturgeon** [comment]
Thanks @josegonzalez!

**Comment by josegonzalez** [comment]
You owe me some ciders for missing out on beers wednesday, and me having to make this pr today.

**Comment by philsturgeon** [comment]
I know :(

**Pull request merged**
