### PR TITLE
Update Dreamhost installed version

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
I've had a side shared hosting with these people for years, I can probably setup some sort of report url for you to pull these numbers through if needed

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thanks @Lewiscowles1986! Shoving in a phpinfo URL would be lovely, like http://jupiterstatus.websiterelay.com/info/

**Comment by Lewiscowles1986** [comment]
I was hoping something like http://dh.codesign2.co.uk/phpversion would be acceptable and you could grep or regex version numbers :+1:

**Comment by philsturgeon** [comment]
Sadly PHP version numbers aren't quite as simple as that, some are a bit mad with extra data on the end. 

We could come up with some format which people can post to consume, I just dont want to build 100 different parsers for 100 different hosts.

**Comment by Lewiscowles1986** [comment]
https://dh.codesign2.co.uk/info.php

**Pull request merged**
