### PR TITLE
Updated the Pagoda Box default version

### PR DESCRIPTION
**Pull request by sanderson**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Hey, do you have public phpinfo's for your major versions?

I've implemented #191 and would love to have your versions updating automatically.

**Comment by sanderson** [comment]
We do:

[php53.gopagoda.io](http://php53.gopagoda.io)
[php54.gopagoda.io](http://php54.gopagoda.io)
[php55.gopagoda.io](http://php55.gopagoda.io)
[php56.gopagoda.io](http://php56.gopagoda.io)
[php70.gopagoda.io](http://php70.gopagoda.io)

**Comment by philsturgeon** [comment]
Thanks! Consider them auto-updating. :)

**Comment by sanderson** [comment]
Awesome. Thx!

**Pull request merged**
