### PR TITLE
fortrabbit update

### PR DESCRIPTION
**Pull request by ostark**
thanks for maintaining phpversions.info

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thanks for keeping the updates coming! If you get bored of sending PRs and want patch level versions to auto-update, let me have a phpinfo URL like this php56.hosteurope-infos.de/phpinfo.php

Then it'll update auto-magically :)

**Comment by ostark** [comment]
Will do, but how to set the default version with the auto-update?

**Comment by philsturgeon** [comment]
I'll write a fix this evening which changes default to look at the version nickname like `56` or `57` so that the full version can be assumed from `host.versions`.

You'll need to come back and let me know when the default changes from `56` to `70` or `71`, but other than that you'll be off the hook.

Sound good?

**Comment by ostark** [comment]
Perfect!

**Pull request merged**
