### PR TITLE
Move App Engine into PaaS. Remove 5.4 reference.

### PR DESCRIPTION
**Pull request by tomwalder**
Latest version validated 2015-08-31 with SDK 1.9.25

### CODE REVIEW

**Comment by philsturgeon** [comment]
Is 5.4 no longer available at all?

**Comment by tomwalder** [comment]
That is correct, they removed it when they went "GA" earlier this year.

If you try and deploy a 5.4 app now, it says...

"PHP 5.4 applications are prevented from being deployed to Google App Engine from any version of the SDK, including older ones. If you need to continue to deploy PHP 5.4 applications for compatibility reasons, you can request that your application be whitelisted for PHP 5.4 deployment by visiting http://goo.gl/qjKEuk."

**Comment by philsturgeon** [comment]
Sorry this fell through the cracks for a bit there. Life is hard.

Double checked their awful shitty docs and found this:

screen shot 2015-12-07 at 10 30 16 am

Looks like it really is only `php55`! Thank you :)

**Comment by philsturgeon** [comment]
Merged manually due to conflicts 4271663

**Comment by tomwalder** [comment]
Ta!

**Pull request closed without merging**
