### PR TITLE
Update hosts.yml

### PR DESCRIPTION
**Pull request by sjlangley**
Add the current App Engine 5.4 PHP versions.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
App engine also supports php 5.5 too, in beta.

**Comment by sjlangley** [comment]
Graham - not quite yet mate

**Comment by GrahamCampbell** [comment]
I'm pretty sure they do. I think it might only be enabled for selected accounts at the moment though.

**Comment by sjlangley** [comment]
Trust me - we had to hold it back until the new year.

**Comment by GrahamCampbell** [comment]
Ok, sure. ;)

**Pull request merged**
