### PR TITLE
Onlime goes PHP 7.0.3 / 5.5.32

### PR DESCRIPTION
**Pull request by onlime**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Thanks! 

Do you have public phpinfo URLs by any chance? I have a new semi-automated approach happening in #229.

**Comment by onlime** [comment]
sure. Would be great to automate this!

- https://php55.onlime.ch/
- https://php56.onlime.ch/
- https://php70.onlime.ch/

**Comment by philsturgeon** [comment]
Perfect! Come back when you change defaults (from 56 to 70 or 70 to 71), other than that, it’s automated! :) 

-- 
Phil Sturgeon

I talk about turtles, bikes and code over here philsturgeon.uk

**Comment by onlime** [comment]
love you, boy!

**Comment by onlime** [comment]
hi Phil. I have upgraded php56 from 5.6.17 to 5.6.18 5hrs ago at 07:15AM CET. The change is not yet reflected on your shared hosts list. How often do you scan the phpinfo URLs?

**Comment by philsturgeon** [comment]
Thanks! It’s semi automated, in the sense that whenever the script runs it pulls the data in. 

Right now I’m doing that locally. Next I’ll hook it up to something, possibly CircleCI nightly builds. 

I’m doing everything in a completely minimal effort way for now. :) 

I ran the update just now so you’re updated.

-- 
Phil Sturgeon

I talk about turtles, bikes and code over here philsturgeon.uk

**Comment by onlime** [comment]
Okidoki, thx. The default version should also get updated, somehow. I would just put 56 as major version key into the default field instead of the full minor version.
Minimal effort sound good. Glad you keep this project running.

**Pull request merged**
