### PR TITLE
Add Relentless Hosting to hosts

### PR DESCRIPTION
**Pull request by kravock**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Do you have a public phpinfo irk for this? Otherwise the patch versions will get out of date which can be frustrating.

**Comment by kravock** [comment]
Not yet, I'll arrange to get them done for each of the versions.

**Comment by kravock** [comment]
Is it possible to update a pull request or do I need to create a new one?

**Comment by philsturgeon** [comment]
The default actually doesn't yet. I'm thinking of switching default to be `56` or `70` so the patch can be assumed from the versions array, but people will still need to come back to change that when they upgrade.

**Pull request merged**
