### PR TITLE
Onlime discontinues legacy PHP 5.4

### PR DESCRIPTION
**Pull request by onlime**
Die 5.4, die! Now as PHP7 heaven is on earth.

### CODE REVIEW

**Comment by onlime** [comment]
seems like there's something wrong with the CircleCI. Guess this is a temporary GitHub problem. If not, you'll fix it soon for sure. You're a smart boy. Wish you a happy ride on your race bike!

**Comment by philsturgeon** [comment]
Thank you! Did you simply remove PHP 5.4 as an option for new folks signing up, or did you force upgrade old users? Dunno which one this site is keeping track of tbh. :D

**Comment by philsturgeon** [comment]
Also, can't! :sob:

img_2864

**Comment by philsturgeon** [comment]
Not only does my bike have a flat tyre, it's also breaking the laws of gravity.

**Comment by onlime** [comment]
wow, wish I could ride on the ceiling! Fix your tire like really fast now and enjoy the f..up laws of gravity.

**Comment by onlime** [comment]
Yesterday we have force upgraded existing customers to PHP 5.5 with the option to downgrade till before Christmas time (Dec 18th). New folks could also still downgrade till that date, but the chances are very low that anybody would want that. The whole migration was announced beginning of October - https://wiki.onlime.ch/dev:php. We learned quite a lot from the last migration away from PHP 5.3 which we enforced way too late. At that time we already warned our custumors that we are not going to be lazy next time - so they were already warned to better jump right to 5.6 and lay back.
Security is our major concern. If any customer insists on keeping his outdated webapp on PHP 5.4, we might not be the right hoster for him.
Thanks for keeping phpversions.info up-to-date!

**Pull request merged**
